#                             _|                _|                          _|
# _|_|_|  _|_|      _|_|_|  _|_|_|_|  _|  _|_|      _|    _|        _|_|_|        _|_|
# _|    _|    _|  _|    _|    _|      _|_|      _|    _|_|        _|    _|  _|  _|    _|
# _|    _|    _|  _|    _|    _|      _|        _|  _|    _|      _|    _|  _|  _|    _|
# _|    _|    _|    _|_|_|      _|_|  _|        _|  _|    _|        _|_|_|  _|    _|_|
#
# Trimaran VFX 2026 - Corto Morrow
# docker-compose.yml - Docker compose file for matrix aio services deployment

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      synapse:
        condition: service_healthy
      oidc:
        condition: service_started
      element:
        condition: service_started
    networks:
      matrix:
        aliases:
          - auth.local
          - synapse.local
          - element.local

  synapse:
    build: ./synapse
    container_name: synapse
    volumes:
      - ./synapse/homeserver.yaml:/data/synapse.yaml:ro
      - ./synapse/modules/:/modules
      - synapse_data:/data
    environment:
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/synapse.yaml
      - PYTHONPATH=/modules
    networks:
      - matrix
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

  element:
    image: vectorim/element-web:latest
    container_name: element
    volumes:
      - ./element/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./element/config.json:/app/config.json:ro
    restart: unless-stopped
    depends_on:
      synapse:
        condition: service_healthy
      oidc:
        condition: service_started
    networks:
      - matrix

  oidc:
    build: ./oidc
    container_name: oidc
    volumes:
      - ./certs:/app/certs:ro
      - provider_data:/app/data
    environment:
#      - OIDC_SYNAPSE_BASEURL=https://api.dev-matrix.trimaran.com
#      - OIDC_PROVIDER_BASEURL=https://auth.dev-matrix.trimaran.com
      - OIDC_FXMANAGER_BASEURL=https://dev-fxmanager.trimaran.com
      - OIDC_SYNAPSE_BASEURL=https://synapse.local
      - OIDC_PROVIDER_BASEURL=https://auth.local
      - OIDC_DEBUG=false
    networks:
      - matrix

networks:
  matrix:
    name: matrix

volumes:
  synapse_data:
  provider_data:
