#                             _|                _|                          _|
# _|_|_|  _|_|      _|_|_|  _|_|_|_|  _|  _|_|      _|    _|        _|_|_|        _|_|
# _|    _|    _|  _|    _|    _|      _|_|      _|    _|_|        _|    _|  _|  _|    _|
# _|    _|    _|  _|    _|    _|      _|        _|  _|    _|      _|    _|  _|  _|    _|
# _|    _|    _|    _|_|_|      _|_|  _|        _|  _|    _|        _|_|_|  _|    _|_|
#
# Trimaran VFX 2026 - Corto Morrow
# nginx.conf - Element Nginx configuration file

server {
    listen 80;
    listen [::]:80;

    root /app;
    index index.html;

    add_header X-Frame-Options "ALLOWALL";

    location / {
        try_files $uri $uri/ /index.html;
    }
}